# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'OverheardUniversity' do

pod "CLHoppingViewController"
pod 'ECSlidingViewController', '~> 2.0.2'
pod 'Facebook-iOS-SDK', '~> 3.23.0'
pod 'iCarousel', '1.7.6'
pod 'JSQMessagesViewController'  
pod 'Onboard'
pod 'Parse', '~> 1.1'
pod "TOMSMorphingLabel", "~> 0.5"
pod 'UIScrollSlidingPages', '~> 1.3'

end

target 'OverheardUniversityTests' do

end

